### ISSUE TITLE
[Balance Druid] Astral Power calculation is sometimes off by 1-3 AP

### ISSUE THREAD

**Issue by lovemonkeyz** [SimCMinMax/AethysRotation#88]
Noticed a lot that during a Lunarstrike/Solar Wrath cast that it says I should Starsurge when I clearly do not have enough Astral Power to cast it directly after. When this occurs it's 1-3 Astral Power always missing. Haven't gotten an exact hang of when it occurs yet, might be only during Chosen of Elune. Will report back

**Comment by Kutikuti** [comment]
I fixed an issue with AP prediction a few days ago : https://github.com/SimCMinMax/AethysRotation/commit/03537cd6689495f37dc5c435a7f61ca22504b9de

Do you have the alpha version ?

**Comment by lovemonkeyz** [comment]
Nope, using Release version, 7.3.2.01 as the latest version available on Twitch/Curseforge, although I do find it odd both sites say the files were updated yesterday yet the version change-log says 7.3.2.01 was released December 3rd, and that's the version both sites let me download/twitch client updates to, is that incorrect? Either way, I've updated it directly from GitHub instead and will test it out.

**Comment by lovemonkeyz** [comment]
Issue still occurs after updating straight from Github repo. Got prompt to cast Starsurge when my finished cast only landed me at 38 Astral Power.

**Comment by Kutikuti** [comment]
Hi, i double checked and that shouldn't happen, I have done a full antorus run and it never occured. What talent setup are you using ?and your legendaries and set

**Comment by Kutikuti** [comment]
Closing this as i've not had issues in the last 20 days, feel free to re-open if that still happen
